language: python
python:
  - "2.7"
  - "3.6"

service:
  - postgresql

before_script:
  - psql -c "create database imager;" -U postgres

install:
  - pip install -r requirements.pip

script:
  - python django_imager/manage.py migrate
  - coverage run django_imager/manage.py test